// Optional CI/browser test. Playwright is a development-only test dependency.
import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';import {createApp} from '../src/server.mjs';
const {chromium}=await import(process.env.BN_PLAYWRIGHT_MODULE||'playwright');
const {server,store}=createApp({file:':memory:'});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true});const errors=[];const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});mkdirSync('systems-browser-artifacts',{recursive:true});
const nav=id=>page.locator(`[data-module="${id}"]`).click();
async function save(form){await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/state')&&r.status()===200),form.locator('button[type=submit],button:not([type])').last().click()]);}
try{
 await page.goto(base);await page.getByRole('heading',{name:'Ügyfélszerző rendszer',exact:true}).waitFor();
 const f=page.locator('[data-form="lead.create"]');await f.getByLabel('Név',{exact:true}).fill('Szintetikus Anna');await f.getByLabel('Email',{exact:true}).fill('anna@example.test');await f.getByLabel('Miben kér segítséget?').fill('<img src=x onerror="alert(1)"> Tanácsadás');await save(f);await page.getByRole('heading',{name:'Szintetikus Anna',exact:true}).waitFor();assert.equal(await page.locator('main img').count(),0);
 await nav('ajanlatkeszito');const p=page.locator('[data-form="proposal.create"]');await p.getByLabel('Ügyféligény és vállalt feladat').fill('Audit');await p.getByLabel('Megnevezés',{exact:true}).fill('Teszt szolgáltatás');await p.getByLabel('Egységár (HUF)').fill('10000');await p.getByLabel('Mennyiség',{exact:true}).fill('2');await save(p);await page.getByRole('button',{name:'Jóváhagyom',exact:true}).waitFor();await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/state')),page.getByRole('button',{name:'Jóváhagyom',exact:true}).click()]);await page.getByRole('button',{name:'Elküldöttnek jelölöm'}).waitFor();
 await nav('meeting-teendo');let m=page.locator('[data-form="meeting.create"]');await m.getByLabel('Megbeszélés neve').fill('Szintetikus egyeztetés');await m.locator('#transcript-file').setInputFiles({name:'leirat.txt',mimeType:'text/plain',buffer:Buffer.from('Anna elküldi az anyagot 2026-10-09.')});await page.waitForFunction(()=>document.querySelector('[name=transcript]').value==='Anna elküldi az anyagot 2026-10-09.');await save(m);m=page.locator('[data-form="meeting.edit"]');await m.getByRole('button',{name:'Teendő hozzáadása'}).click();await m.getByLabel('Teendő',{exact:true}).fill('Anyag elküldése');await m.getByLabel('Felelős (ha ismert)').fill('Anna');await m.getByLabel('Határidő (ha ismert)').fill('2026-10-09');await m.getByLabel('Szó szerinti részlet a leiratból').fill('Anna elküldi az anyagot 2026-10-09.');await save(m);await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/state')),page.getByRole('button',{name:'Jóváhagyás és feladatok'}).click()]);await nav('ugyfelkezelo');await page.getByRole('heading',{name:'Anyag elküldése'}).waitFor();
 await page.getByRole('button',{name:'Vállalkozás beállításai'}).click();
 const profile=page.locator('[data-form="profile.save"]');await profile.getByLabel('Vállalkozás neve').fill('Szintetikus vállalkozás');await profile.getByLabel('Utánkövetés munkanapjai (vesszővel)').fill('2,5');await save(profile);await page.reload();await page.getByRole('button',{name:'Vállalkozás beállításai'}).click();await page.getByLabel('Vállalkozás neve').waitFor();assert.equal(await page.getByLabel('Vállalkozás neve').inputValue(),'Szintetikus vállalkozás');assert.equal(await page.getByLabel('Utánkövetés munkanapjai (vesszővel)').inputValue(),'2,5');await nav('ugyfelkezelo');
 await page.screenshot({path:'systems-browser-artifacts/desktop.png',fullPage:true});
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const id of ['ugyfelszerzo','erdeklodo-minosito','ajanlatkeszito','ugyfel-onboarding','ugyfelkezelo','meeting-teendo','utankoveto','tudasrendszer','heti-attekinto']){await nav(id);assert.equal(await page.locator('h1').count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Horizontal overflow: ${width}/${id}`);}await page.getByRole('button',{name:'Vállalkozás beállításai'}).click();await page.getByRole('heading',{name:'Vállalkozási profil'}).waitFor();}
 await page.setViewportSize({width:390,height:844});await nav('meeting-teendo');await page.screenshot({path:'systems-browser-artifacts/mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS browser: inquiry + XSS rendering + proposal approval + meeting/task + 9 modules at 3 widths + no console errors');
}finally{await browser.close();await new Promise(r=>server.close(r));store.close();}
