import { DatabaseSync } from 'node:sqlite';
import { randomUUID, createHash } from 'node:crypto';
import { mkdirSync, readFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { kinds } from './catalog.mjs';
export class Fault extends Error { constructor(message,status=400){super(message);this.status=status;} }
const requireValue=(ok,message,status=400)=>{if(!ok)throw new Fault(message,status);};
const text=(v,max=50000)=>{requireValue(typeof v==='string'&&v.trim().length>0&&v.length<=max,'Hiányzó vagy túl hosszú szöveg.');return v.trim();};
const email=v=>{v=text(v,254).toLowerCase();requireValue(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),'Hibás email-cím.');return v;};
const integer=(v,min=0)=>{requireValue(Number.isSafeInteger(v)&&v>=min,'Egész szám szükséges.');return v;};
const date=v=>{requireValue(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v).toISOString().slice(0,10)===v,'Hibás dátum.');return v;};
const now=()=>new Date().toISOString();
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const defaultProfile=JSON.parse(readFileSync(new URL('../profile.example.json',import.meta.url)));
export function qualify(input,policy={weights:{service:40,scope:20,budget:20,timing:20},critical:['service','scope']}){
 const weights=policy.weights;requireValue(weights&&Object.keys(weights).length===4&&['service','scope','budget','timing'].every(k=>Number.isFinite(weights[k])&&weights[k]>0)&&Object.values(weights).reduce((a,b)=>a+b,0)===100,'A négy súly összege 100 legyen.');requireValue(Array.isArray(policy.critical)&&policy.critical.every(k=>k in weights),'Hibás kritikus szempont.');let total=0,known=0;
 for(const [k,w]of Object.entries(weights)){const v=input[k];if(v==null)continue;requireValue([0,.5,1].includes(v),'A pontozás 0, 0.5, 1 vagy ismeretlen.');known+=w;total+=w*v;}
 const coverage=known/100,score=known?Math.round(total/known*1000)/10:null;
 return {score,coverage,decision:input.excluded===true?'not-fit':coverage<.8||['service','scope',...policy.critical].some(k=>input[k]==null)?'clarify':score>=70?'fit':'review',weights};
}
export function proposalTotals(items){
 requireValue(Array.isArray(items)&&items.length>0&&items.length<=100,'1–100 ajánlati tétel szükséges.');
 let net=0,tax=0;const lines=items.map(item=>{const name=text(item.name,200),quantity=integer(item.quantity,1),unitMinor=integer(item.unitMinor);requireValue(Number.isFinite(item.taxPercent)&&item.taxPercent>=0&&item.taxPercent<=100,'Hibás adókulcs.');const n=integer(quantity*unitMinor),t=integer(Math.round(n*item.taxPercent/100));net=integer(net+n);tax=integer(tax+t);return {name,quantity,unitMinor,taxPercent:item.taxPercent,net:n,tax:t,gross:n+t};});
 return {items:lines,net,tax,gross:integer(net+tax)};
}
// RFC4180 quoted fields, including escaped quotes and embedded newlines.
export function parseCSV(source){
 text(source,1000000);const rows=[];let row=[],field='',quoted=false,closed=false;
 for(let i=0;i<=source.length;i++){const c=source[i];if(quoted){if(c==='"'&&source[i+1]==='"'){field+='"';i++;}else if(c==='"'){quoted=false;closed=true;}else{requireValue(c!==undefined,'Lezáratlan CSV idézőjel.');field+=c;}continue;}
 if(c==='"'){requireValue(!field&&!closed,'Hibás CSV idézőjel.');quoted=true;}else if(c===','||c==='\n'||c===undefined){row.push(field);field='';closed=false;if(c!==','){if(row.some(Boolean))rows.push(row);row=[];}}else if(c==='\r'&&source[i+1]==='\n'){}else{requireValue(!closed,'Hibás CSV mező.');field+=c;}}
 requireValue(rows.length>1&&rows.length<=1001,'A CSV fejlécet és 1–1000 sort tartalmazzon.');const headers=rows.shift().map(s=>s.replace(/^\uFEFF/,''));requireValue(new Set(headers).size===headers.length,'Ismételt CSV oszlop.');return rows.map(r=>{requireValue(r.length===headers.length,'Eltérő CSV oszlopszám.');return Object.fromEntries(headers.map((h,i)=>[h,r[i]]));});
}
function localDate(iso,timezone){return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso));}
function localNine(day,timezone){let d=new Date(`${day}T09:00:00Z`);for(let i=0;i<3;i++){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));const seen=Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute);d=new Date(+d+(Date.parse(`${day}T09:00:00Z`)-seen));}return d.toISOString();}
export function followupDates(base,timezone,offsets=[3,7]){requireValue(Array.isArray(offsets)&&offsets.length>0&&offsets.length<=2&&offsets.every(n=>Number.isInteger(n)&&n>0&&n<=365)&&new Set(offsets).size===offsets.length,'Legfeljebb két különböző, 1–365 munkanapos lépés szükséges.');return offsets.map(n=>{let d=new Date(localDate(base,timezone)+'T12:00:00Z');for(let passed=0;passed<n;){d.setUTCDate(d.getUTCDate()+1);if(![0,6].includes(d.getUTCDay()))passed++;}return localNine(d.toISOString().slice(0,10),timezone);});}
export class Store{
 constructor(file=':memory:'){if(file!==':memory:')mkdirSync(dirname(file),{recursive:true});this.db=new DatabaseSync(file);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,version INTEGER NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY AUTOINCREMENT,record_id TEXT,action TEXT NOT NULL,at TEXT NOT NULL,payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS requests(key TEXT PRIMARY KEY,digest TEXT NOT NULL,result TEXT NOT NULL);`);this.db.prepare('INSERT OR IGNORE INTO meta VALUES (?,?)').run('schema','1');this.db.prepare('INSERT OR IGNORE INTO meta VALUES (?,?)').run('profile',JSON.stringify(defaultProfile));requireValue(this.db.prepare('SELECT value FROM meta WHERE key=?').get('schema').value==='1','Nem támogatott adatbázis-verzió.');}
 close(){this.db.close();}
 profile(){const p=JSON.parse(this.db.prepare('SELECT value FROM meta WHERE key=?').get('profile').value);return {...p,version:p.version||1};}
 list(kind){requireValue(kinds.includes(kind),'Ismeretlen adattípus.');return this.db.prepare('SELECT * FROM records WHERE kind=? ORDER BY created_at DESC,id').all(kind).map(r=>({...JSON.parse(r.data),id:r.id,kind:r.kind,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));}
 get(id,kind){const r=this.db.prepare('SELECT * FROM records WHERE id=?').get(id);requireValue(r&&(!kind||r.kind===kind),'Nem található.',404);return {...JSON.parse(r.data),id:r.id,kind:r.kind,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at};}
 save(kind,data,old=null){requireValue(kinds.includes(kind),'Ismeretlen adattípus.');const id=old?.id||randomUUID(),at=now(),version=(old?.version||0)+1;const clean={...data};for(const k of ['id','kind','version','createdAt','updatedAt'])delete clean[k];this.db.prepare('INSERT INTO records VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,data=excluded.data,updated_at=excluded.updated_at').run(id,kind,version,JSON.stringify(clean),old?.createdAt||at,at);this.db.prepare('INSERT INTO events(record_id,action,at,payload) VALUES (?,?,?,?)').run(id,`${kind}.${old?'updated':'created'}`,at,JSON.stringify({version,data:clean}));return this.get(id);}
 old(input,kind){const r=this.get(text(input.id,100),kind);requireValue(r.version===input.version,'Közben módosult. Frissítsd az oldalt.',409);return r;}
 cached(action,input,key){requireValue(typeof key==='string'&&/^[\w-]{8,100}$/.test(key),'Érvényes idempotenciakulcs szükséges.');const row=this.db.prepare('SELECT * FROM requests WHERE key=?').get(key);if(!row)return undefined;requireValue(row.digest===hash({action,input}),'A kulcs már más művelethez tartozik.',409);return JSON.parse(row.result);}
 execute(action,input={},key,effect){const cached=this.cached(action,input,key);if(cached!==undefined)return cached;this.db.exec('BEGIN IMMEDIATE');try{const result=effect?effect():this.action(action,input);this.db.prepare('INSERT INTO requests VALUES (?,?,?)').run(key,hash({action,input}),JSON.stringify(result));this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 assertSources(refs){requireValue(Array.isArray(refs),'Hiányzó forrásállapot.',409);for(const ref of refs){const r=this.get(ref.id);requireValue(r.version===ref.version&&r.status!=='deleted','A forrás időközben megváltozott. Kérj új AI-tervezetet.',409);}return true;}
 async prepareResult(action,input,key,prepare){const cached=this.cached(action,input,key);if(cached!==undefined)return cached;this.readPending??=new Map();const digest=hash({action,input}),existing=this.readPending.get(key);if(existing){requireValue(existing.digest===digest,'A kulcs már más művelethez tartozik.',409);return existing.promise;}const promise=(async()=>{const result=await prepare();return this.execute(action,input,key,()=>result);})();this.readPending.set(key,{digest,promise});try{return await promise;}finally{this.readPending.delete(key);}}
 async prepareOnce(input,key,prepare){const action='meeting.prepare',cached=this.cached(action,input,key);if(cached!==undefined)return cached;this.pending??=new Map();const digest=hash(input),existing=this.pending.get(key);if(existing){requireValue(existing.digest===digest,'A kulcs már más művelethez tartozik.',409);return existing.promise;}const promise=(async()=>{const record=this.old(input,'meeting');requireValue(record.status!=='approved','Már jóváhagyott meeting.',409);const draft=await prepare(record);return this.execute(action,input,key,()=>this.action('meeting.edit',{id:input.id,version:input.version,summary:draft.summary,tasks:draft.tasks,decisions:draft.decisions}));})();this.pending.set(key,{digest,promise});try{return await promise;}finally{this.pending.delete(key);}}
 action(action,p){
  switch(action){
   case 'profile.save':{const previous=this.profile();requireValue(p.version===previous.version,'Közben módosult a profil. Frissítsd az oldalt.',409);const policy=p.qualificationPolicy||previous.qualificationPolicy||{weights:{service:40,scope:20,budget:20,timing:20},critical:['service','scope']};qualify({},policy);const offsets=p.followupOffsets||previous.followupOffsets||[3,7];followupDates(now(),p.timezone,offsets);const profile={version:previous.version+1,qualificationPolicy:policy,name:text(p.name,200),services:Array.isArray(p.services)?p.services.map(s=>text(s,200)):[],minimumBudget:integer(p.minimumBudget),currency:text(p.currency,3).toUpperCase(),timezone:text(p.timezone,100),bookingUrl:p.bookingUrl||'',tone:text(p.tone,500),followupOffsets:offsets,catalog:p.catalog||[]};requireValue(profile.services.length>0,'Legalább egy szolgáltatás szükséges.');requireValue(['HUF','EUR','USD','GBP','CHF','CAD','AUD','PLN','CZK','RON'].includes(profile.currency),'A támogatott két tizedesjegyű pénznemek egyikét válaszd.');requireValue(Array.isArray(profile.catalog)&&new Set(profile.catalog.map(c=>c.id)).size===profile.catalog.length,'Ismételt szolgáltatásazonosító.');new Intl.DateTimeFormat('en',{timeZone:profile.timezone});if(profile.bookingUrl)requireValue(new URL(profile.bookingUrl).protocol==='https:','A foglalási link HTTPS legyen.');if(profile.catalog.length)proposalTotals(profile.catalog.map(c=>({...c,quantity:1})));this.db.prepare('UPDATE meta SET value=? WHERE key=?').run(JSON.stringify(profile),'profile');return profile;}
   case 'lead.create':{const name=text(p.name,200),address=email(p.email),need=text(p.need);return this.save('lead',{name,email:address,need,stage:'new',replied:false,unsubscribed:false,source:p.source==='csv'?'csv':'manual',summary:need.slice(0,600),draft:`Kedves ${name}! Köszönjük az érdeklődést. Pontosítsuk az igényt és a következő lépést egy egyeztetésen.`,qualification:null});}
   case 'lead.import':{const digest='import:lead:'+hash(p.csv),prior=this.db.prepare('SELECT value FROM meta WHERE key=?').get(digest);if(prior)return JSON.parse(prior.value).map(id=>this.get(id));const rows=parseCSV(p.csv);requireValue(rows.every(r=>r.name&&r.email&&r.need),'Kötelező CSV oszlopok: name,email,need.');const result=rows.map(r=>this.action('lead.create',{...r,source:'csv'}));this.db.prepare('INSERT INTO meta VALUES (?,?)').run(digest,JSON.stringify(result.map(r=>r.id)));return result;}
   case 'lead.qualify':{const r=this.old(p,'lead');return this.save('lead',{...r,qualification:{...qualify(p.scores,this.profile().qualificationPolicy),profileVersion:this.profile().version,scores:p.scores,reason:text(p.reason,2000)}},r);}
   case 'lead.stage':{const r=this.old(p,'lead');requireValue(['new','qualified','booked','proposal','won','lost','replied','unsubscribed'].includes(p.stage),'Hibás állapot.');const next=this.save('lead',{...r,stage:p.stage,replied:r.replied||p.stage==='replied',unsubscribed:r.unsubscribed||p.stage==='unsubscribed'},r);if(['won','lost','replied','unsubscribed'].includes(p.stage))for(const f of this.list('followup').filter(f=>f.leadId===r.id&&f.status==='draft'))this.save('followup',{...f,status:'cancelled',cancelReason:p.stage},f);return next;}
   case 'proposal.create':{const lead=this.get(p.leadId,'lead');return this.save('proposal',{leadId:lead.id,name:lead.name,scope:text(p.scope),validUntil:p.validUntil?date(p.validUntil):null,terms:p.terms?text(p.terms,10000):'',timeline:p.timeline?text(p.timeline,2000):'',currency:this.profile().currency,...proposalTotals(p.items),revision:1,status:'draft',approvedRevision:null});}
   case 'proposal.edit':{const r=this.old(p,'proposal');return this.save('proposal',{...r,scope:text(p.scope),validUntil:p.validUntil?date(p.validUntil):null,terms:p.terms?text(p.terms,10000):'',timeline:p.timeline?text(p.timeline,2000):'',...proposalTotals(p.items),revision:r.revision+1,status:'draft',approvedRevision:null},r);}
   case 'proposal.approve':{const r=this.old(p,'proposal');requireValue(!r.validUntil||r.validUntil>=localDate(now(),this.profile().timezone),'Lejárt ajánlat: új változat és érvényesség szükséges.');return this.save('proposal',{...r,status:'approved',approvedRevision:r.revision},r);}
   case 'proposal.reportSent':{const r=this.old(p,'proposal');requireValue(r.approvedRevision===r.revision&&r.status==='approved','Előbb hagyd jóvá a jelenlegi ajánlatot.');return this.save('proposal',{...r,status:'reported_sent',reportedSentAt:now()},r);}
   case 'project.create':{const name=text(p.name,200);let proposalId=null;if(p.proposalId){const r=this.get(p.proposalId,'proposal');requireValue(r.approvedRevision===r.revision&&['approved','reported_sent'].includes(r.status),'Jóváhagyott ajánlat szükséges.');requireValue(!r.validUntil||r.validUntil>=localDate(now(),this.profile().timezone),'Lejárt ajánlatból nem indítható projekt.');proposalId=r.id;}requireValue(p.confirmed===true,'Erősítsd meg, hogy az ügyfél megrendelte a munkát.');if(proposalId)requireValue(!this.list('project').some(r=>r.proposalId===proposalId),'Ehhez az ajánlathoz már tartozik projekt.',409);return this.save('project',{name,proposalId,proposalSnapshot:proposalId?this.get(proposalId,'proposal'):null,confirmed:true,status:'onboarding',items:(Array.isArray(p.checklist)&&p.checklist.length?p.checklist.map(label=>text(label,500)):['Kapcsolattartó és elérhetőség','Cél és határidő','Szükséges dokumentumok']).map(label=>({id:randomUUID(),label,required:true,verified:false})),welcome:`Üdvözlünk! Az induláshoz kérjük a kapcsolattartó adatait, a célokat és a szükséges dokumentumokat.`});}
   case 'project.verify':{const r=this.old(p,'project');requireValue(r.status!=='active'||p.verified===true,'Aktív projektnél az indulási feltétel nem vonható vissza.',409);requireValue(r.items.some(i=>i.id===p.itemId),'Hiányzó ellenőrzési tétel.');return this.save('project',{...r,items:r.items.map(i=>i.id===p.itemId?{...i,verified:p.verified===true}:i)},r);}
   case 'project.start':{const r=this.old(p,'project');requireValue(r.items.every(i=>!i.required||i.verified),'Még hiányoznak kötelező adatok.');return this.save('project',{...r,status:'active'},r);}
   case 'contact.edit':{const r=this.old(p,'contact');return this.save('contact',{...r,name:text(p.name,200),email:email(p.email),notes:p.notes?text(p.notes):'',nextStep:p.nextStep?text(p.nextStep,1000):''},r);}
   case 'contact.create':return this.save('contact',{name:text(p.name,200),email:email(p.email),notes:p.notes?text(p.notes):'',nextStep:p.nextStep?text(p.nextStep,1000):''});
   case 'task.create':{if(p.projectId)this.get(p.projectId,'project');return this.save('task',{title:text(p.title,500),owner:p.owner?text(p.owner,200):null,due:p.due?date(p.due):null,projectId:p.projectId||null,status:'open',evidence:p.evidence||null,meetingId:p.meetingId||null});}
   case 'task.edit':{const r=this.old(p,'task');return this.save('task',{...r,title:text(p.title,500),owner:p.owner?text(p.owner,200):null,due:p.due?date(p.due):null},r);}
   case 'task.complete':{const r=this.old(p,'task');return this.save('task',{...r,status:'done',completedAt:now()},r);}
   case 'meeting.create':{const transcript=text(p.transcript);return this.save('meeting',{title:text(p.title,200),date:date(p.date),transcript,status:'review',summary:transcript.slice(0,600),tasks:[],decisions:[],mode:'manual'});}
   case 'meeting.edit':{const r=this.old(p,'meeting');requireValue(r.status!=='approved','A már jóváhagyott meeting nem írható át.');requireValue(Array.isArray(p.tasks)&&p.tasks.length<=100,'Legfeljebb 100 feladat.');const tasks=p.tasks.map(t=>{const evidence=text(t.evidence,2000);requireValue(r.transcript.includes(evidence),'A bizonyíték nem szerepel a leiratban.');return {title:text(t.title,500),owner:t.owner?text(t.owner,200):null,due:t.due?date(t.due):null,evidence};});const decisions=(p.decisions||[]).map(d=>{requireValue(r.transcript.includes(text(d.evidence,2000)),'A döntés bizonyítéka hiányzik.');return {text:text(d.text,1000),evidence:d.evidence};});return this.save('meeting',{...r,summary:text(p.summary),tasks,decisions},r);}
   case 'meeting.approve':{const r=this.old(p,'meeting');requireValue(r.status!=='approved','Már jóváhagyva.',409);for(const t of r.tasks)this.action('task.create',{...t,meetingId:r.id});return this.save('meeting',{...r,status:'approved',followupDraft:`Megbeszélés: ${r.title}\n${r.summary}\n${r.tasks.map(t=>`• ${t.title} (${t.owner||'felelős tisztázandó'}; ${t.due||'határidő tisztázandó'})`).join('\n')}`},r);}
   case 'followup.plan':{const lead=this.get(p.leadId,'lead');requireValue(!lead.replied&&!lead.unsubscribed&&!['won','lost'].includes(lead.stage),'Ennél az érdeklődőnél leállt az utánkövetés.');requireValue(!this.list('followup').some(f=>f.leadId===lead.id),'Már van utánkövetési sorozat.',409);return followupDates(now(),this.profile().timezone,this.profile().followupOffsets).map((due,i)=>this.save('followup',{leadId:lead.id,name:lead.name,step:i+1,due,policyVersion:this.profile().version,status:'draft',draft:`Kedves ${lead.name}! Szeretnék visszatérni az érdeklődésedre: ${lead.need.slice(0,200)}. Aktuális még az egyeztetés?`}));}
   case 'followup.edit':{const r=this.old(p,'followup');requireValue(r.status==='draft','Csak tervezet módosítható.');return this.save('followup',{...r,draft:text(p.draft,10000)},r);}
   case 'followup.cancel':{const r=this.old(p,'followup');requireValue(r.status==='draft','Csak tervezet állítható le.');return this.save('followup',{...r,status:'cancelled',cancelReason:'manual'},r);}
   case 'followup.reportSent':{const f=this.old(p,'followup'),lead=this.get(f.leadId,'lead');requireValue(f.status==='draft'&&!lead.replied&&!lead.unsubscribed&&!['won','lost'].includes(lead.stage),'Nem küldhető.');requireValue(p.confirmed===true,'Csak a ténylegesen elküldött üzenetet jelöld.');return this.save('followup',{...f,status:'reported_sent',reportedSentAt:now()},f);}
   case 'document.create':{requireValue(['public','internal'].includes(p.visibility),'Jelöld a láthatóságot.');return this.save('document',{title:text(p.title,200),body:text(p.body),visibility:p.visibility,status:'active'});}
   case 'document.edit':{const r=this.old(p,'document');requireValue(r.status!=='deleted','Törölt forrás nem szerkeszthető.');requireValue(['internal','public'].includes(p.visibility),'Hibás láthatóság.');return this.save('document',{...r,title:text(p.title,200),body:text(p.body),visibility:p.visibility,status:'active'},r);}
   case 'ticket.resolve':{const r=this.old(p,'ticket');return this.save('ticket',{...r,status:'resolved',answer:text(p.answer,10000)},r);}
   case 'document.delete':{const r=this.old(p,'document');return this.save('document',{...r,body:'',status:'deleted'},r);}
   case 'knowledge.ask':{requireValue(p.audience===undefined||['public','internal'].includes(p.audience),'Ismeretlen keresési jogosultság.');const audience=p.audience||'public';const question=text(p.question,1000),terms=question.toLocaleLowerCase('hu').match(/[\p{L}\p{N}]{3,}/gu)||[];const candidates=this.list('document').filter(d=>d.status==='active'&&(audience!=='public'||d.visibility==='public')).map(d=>({d,score:terms.filter(t=>(d.title+' '+d.body).toLocaleLowerCase('hu').includes(t)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);if(!candidates.length){const ticket=this.save('ticket',{question,status:'open',reason:'Nincs megfelelő forrás.'});return {answer:null,ticketId:ticket.id,sources:[],mode:'retrieval'};}return {answer:'Kapcsolódó forrásrészletek; ezek nem ellenőrzött válaszok a kérdésre.',sources:candidates.map(({d})=>({id:d.id,version:d.version,title:d.title,quote:d.body.slice(0,1200)})),mode:'retrieval'};}
   case 'payment.import':{const rows=parseCSV(p.csv);requireValue(rows.every(r=>r.amount&&r.currency&&r.type&&r.date&&r.reference),'CSV oszlopok: amount,currency,type,date,reference');return rows.map(r=>{requireValue(/^\d+(?:\.\d{1,2})?$/.test(r.amount),'Hibás összeg.');return this.action('payment.create',{...r,amountMinor:Math.round(Number(r.amount)*100)});});}
   case 'payment.create':{const amountMinor=integer(p.amountMinor,1),currency=text(p.currency,3).toUpperCase();requireValue(/^[A-Z]{3}$/.test(currency),'Hibás pénznem.');requireValue(['payment','refund'].includes(p.type),'Hibás pénzmozgás.');const value={amountMinor,currency,type:p.type,date:date(p.date),reference:text(p.reference,200)};const existing=this.list('payment').find(r=>r.reference===value.reference&&r.type===value.type&&r.currency===currency);if(existing){requireValue(existing.amountMinor===amountMinor&&existing.date===value.date,'Ez a pénzmozgás-hivatkozás eltérő adatokkal már szerepel.',409);return existing;}return this.save('payment',value);}
   case 'review.create':{const start=date(p.start),d=new Date(start+'T12:00:00Z');requireValue(d.getUTCDay()===1,'A hét kezdete hétfő legyen.');d.setUTCDate(d.getUTCDate()+7);const end=d.toISOString().slice(0,10),timezone=this.profile().timezone;const inside=iso=>{const day=localDate(iso,timezone);return day>=start&&day<end;};const all=this.db.prepare('SELECT * FROM events ORDER BY seq').all().filter(e=>inside(e.at)&&['lead','proposal','project','task','contact','meeting','followup'].includes(e.action.split('.')[0])),totals={};for(const r of this.list('payment').filter(r=>r.date>=start&&r.date<end)){totals[r.currency]??={payments:0,refunds:0,net:0};totals[r.currency][r.type==='payment'?'payments':'refunds']+=r.amountMinor;totals[r.currency].net+=r.type==='payment'?r.amountMinor:-r.amountMinor;}
    const state=new Map();for(const e of this.db.prepare('SELECT * FROM events ORDER BY seq').all()){if(localDate(e.at,timezone)>=end)continue;state.set(e.record_id,{kind:e.action.split('.')[0],...JSON.parse(e.payload).data});}const counts={leads:all.filter(e=>e.action==='lead.created').length,bookings:all.filter(e=>e.action==='lead.updated'&&JSON.parse(e.payload).data.stage==='booked').map(e=>e.record_id).filter((v,i,a)=>a.indexOf(v)===i&&state.get(v)?.stage==='booked').length,proposals:all.filter(e=>e.action==='proposal.created').length,won:all.filter(e=>e.action==='lead.updated'&&JSON.parse(e.payload).data.stage==='won').map(e=>e.record_id).filter((v,i,a)=>a.indexOf(v)===i).length,openTasks:[...state.values()].filter(r=>r.kind==='task'&&r.status==='open').length};return this.save('review',{start,end,timezone,counts,totals,source:'A helyi adatbázisban rögzített események',freshAt:now(),dataState:all.length||Object.keys(totals).length?'recorded':'no-events',recommendations:counts.openTasks?[`${counts.openTasks} nyitott feladat felelősét és határidejét érdemes áttekinteni.`]:[],revision:this.list('review').filter(r=>r.start===start).length+1});}
   default:throw new Fault('Ismeretlen művelet.',404);
  }
 }
 export(){const payload={schema:1,profile:this.profile(),imports:this.db.prepare("SELECT * FROM meta WHERE key LIKE 'import:%' ORDER BY key").all(),records:this.db.prepare('SELECT * FROM records ORDER BY id').all(),events:this.db.prepare('SELECT * FROM events ORDER BY seq').all(),requests:this.db.prepare('SELECT * FROM requests ORDER BY key').all()};return {payload,sha256:hash(payload)};}
 restore(bundle){requireValue(bundle?.payload?.schema===1&&hash(bundle.payload)===bundle.sha256,'Sérült vagy nem támogatott mentés.');requireValue(!this.db.prepare('SELECT id FROM records LIMIT 1').get(),'Visszaállítás csak üres adatbázisba.',409);this.db.exec('BEGIN IMMEDIATE');try{const b=bundle.payload;this.action('profile.save',{...b.profile,version:this.profile().version});this.db.prepare('UPDATE meta SET value=? WHERE key=?').run(JSON.stringify(b.profile),'profile');for(const m of b.imports||[]){requireValue(/^import:lead:[a-f0-9]{64}$/.test(m.key),'Hibás importjelölő.');this.db.prepare('INSERT INTO meta VALUES (?,?)').run(m.key,m.value);}for(const r of b.records){requireValue(kinds.includes(r.kind)&&r.version>0,'Hibás rekord.');JSON.parse(r.data);this.db.prepare('INSERT INTO records VALUES (?,?,?,?,?,?)').run(r.id,r.kind,r.version,r.data,r.created_at,r.updated_at);}for(const e of b.events)this.db.prepare('INSERT INTO events VALUES (?,?,?,?,?)').run(e.seq,e.record_id,e.action,e.at,e.payload);for(const q of b.requests)this.db.prepare('INSERT INTO requests VALUES (?,?,?)').run(q.key,q.digest,q.result);this.db.exec('COMMIT');return {restored:b.records.length};}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
