import {csvCell} from './csv.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,current,noticeTimer;
const labels={new:'Új',qualified:'Minősített',booked:'Időpont egyeztetve',proposal:'Ajánlat alatt',won:'Ügyfél lett',lost:'Lezárva',replied:'Válaszolt',unsubscribed:'Leiratkozott',draft:'Tervezet',approved:'Jóváhagyva',reported_sent:'Kézzel elküldöttnek jelölve',cancelled:'Leállítva',onboarding:'Adatbekérés',active:'Aktív',open:'Nyitott',done:'Kész',review:'Ellenőrzésre vár',fit:'Illeszkedik',clarify:'Pontosítás szükséges','not-fit':'Nem illeszkedik'};
function notice(message){$('#notice').textContent=message;$('#notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('show'),7000);}
async function request(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-BN-CSRF':state.csrf,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
async function action(name,input){return request('/api/action',{action:name,input});}
async function refresh(){const r=await fetch('/api/state');if(!r.ok)throw new Error('Nem sikerült kapcsolódni.');state=await r.json();current=current||state.modules[0].id;render();}
const field=(name,label,type='text',value='',required=true)=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
const area=(name,label,value='',required=true)=>`<label>${esc(label)}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea></label>`;
const select=(name,label,options)=>`<label>${esc(label)}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`;
const button=(name,label,record,extra={})=>`<button data-action="${name}" data-input="${esc(JSON.stringify({id:record.id,version:record.version,...extra}))}">${label}</button>`;
const form=(name,title,html,label='Mentés',extra={})=>`<section class="panel"><h2>${title}</h2><form data-form="${name}" data-extra="${esc(JSON.stringify(extra))}">${html}<button type="submit">${label}</button></form></section>`;
const cards=(items,fn)=>items.length?items.map(fn).join(''):'<p class="empty">Még nincs rögzített adat. Az űrlappal kezdheted el.</p>';
const card=(r,html)=>`<article class="card"><span class="badge">${esc(labels[r.status||r.stage]||r.status||r.stage||'Rögzítve')}</span><h3>${esc(r.name||r.title||r.start||r.question)}</h3>${html}<div class="meta">${esc(r.updatedAt?.slice(0,16).replace('T',' '))} · ${r.version}. változat</div></article>`;
function rowEditor(type,r={}){
 const remove='<button type="button" class="secondary" data-remove-row>Eltávolítás</button>';
 if(type==='items'||type==='catalog')return `<fieldset data-row="${type}" data-id="${esc(r.id||'')}"><legend>Szolgáltatási tétel</legend>${field('itemName','Megnevezés','text',r.name||'')}${type==='items'?field('quantity','Mennyiség','number',r.quantity||1):''}<label>Egységár (${esc(state.profile.currency)})<input type="number" name="price" min="0" step="0.01" value="${r.unitMinor!=null?r.unitMinor/100:''}" required></label><label>Adókulcs (%)<input type="number" name="tax" min="0" max="100" step="0.01" value="${r.taxPercent??0}" required></label>${remove}</fieldset>`;
 if(type==='tasks')return `<fieldset data-row="tasks"><legend>Teendő</legend>${field('taskTitle','Teendő','text',r.title||'')}${field('taskOwner','Felelős (ha ismert)','text',r.owner||'',false)}${field('taskDue','Határidő (ha ismert)','date',r.due||'',false)}${area('taskEvidence','Szó szerinti részlet a leiratból',r.evidence||'')}${remove}</fieldset>`;
 return `<fieldset data-row="decisions"><legend>Döntés</legend>${field('decisionText','Döntés','text',r.text||'')}${area('decisionEvidence','Szó szerinti részlet a leiratból',r.evidence||'')}${remove}</fieldset>`;
}
function rows(type,values=[]){return `<div data-rows="${type}">${values.map(v=>rowEditor(type,v)).join('')}</div><button type="button" class="secondary" data-add-row="${type}">${{items:'Új ajánlati tétel',catalog:'Új szolgáltatás',tasks:'Teendő hozzáadása',decisions:'Döntés hozzáadása'}[type]}</button>`;}
function readRows(form,type){return [...form.querySelectorAll(`[data-row="${type}"]`)].map(row=>{const v=name=>row.querySelector(`[name="${name}"]`).value;if(type==='items'||type==='catalog'){const amount=v('price');if(!/^\d+(?:\.\d{1,2})?$/.test(amount))throw new Error('Az ár legfeljebb két tizedesjegyet tartalmazhat.');const item={name:v('itemName'),unitMinor:Math.round(Number(amount)*100),taxPercent:Number(v('tax'))};return type==='items'?{...item,quantity:Number(v('quantity'))}:{...item,id:row.dataset.id||crypto.randomUUID()};}if(type==='tasks')return {title:v('taskTitle'),owner:v('taskOwner')||null,due:v('taskDue')||null,evidence:v('taskEvidence')};return {text:v('decisionText'),evidence:v('decisionEvidence')};});}
const leadSelect=()=>select('leadId','Érdeklődő',state.data.lead.map(r=>[r.id,`${r.name} · ${r.email}`]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:state.profile.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function header(){const m=state.modules.find(m=>m.id===current);return `<div class="eyebrow">${esc(m?.group||'Saját munkatér')}</div><h1>${esc(m?.title||'Vállalkozás beállításai')}</h1><p class="lead">${esc(m?.description||'Ezekből az adatokból készülnek a rendszer alapbeállításai.')}<br><small>Helyi adatbázis · emberi ellenőrzés · ${state.mode==='local'?'kézi és szabályalapú előkészítés':'AI előkészítés külön indítható'}</small></p>`;}
function render(){
 $('#nav').innerHTML=state.modules.map(m=>`<button data-module="${m.id}" ${current===m.id?'aria-current="page"':''}>${m.number.toString().padStart(2,'0')} &nbsp;${esc(m.title)}</button>`).join('');
 let html='';const d=state.data;
 if(['ugyfelszerzo','erdeklodo-minosito'].includes(current)){
 html=form('lead.create','Új érdeklődés',field('name','Név')+field('email','Email','email')+area('need','Miben kér segítséget?'),'Érdeklődés rögzítése')+`<section><h2>Érdeklődők (${d.lead.length})</h2>${cards(d.lead,r=>card(r,`<p>${esc(r.email)}<br>${esc(r.need)}</p>${r.qualification?`<p>Minősítés: <strong>${esc(labels[r.qualification.decision])}</strong> · ${r.qualification.score??'–'} pont · ${Math.round(r.qualification.coverage*100)}% ismert adat</p>`:''}<details><summary>Minősítés és állapot</summary><form data-form="lead.qualify" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${['service','scope','budget','timing'].map((k,i)=>select(k,['Szolgáltatás illeszkedése','Feladat tisztázottsága','Költségkeret','Időzítés'][i],[['','Ismeretlen'],['1','Illeszkedik'],['0.5','Részben'],['0','Nem illeszkedik']])).join('')}<label class="check"><input type="checkbox" name="excluded">Kizáró ok fennáll</label>${area('reason','Indok és forrás')}<button>Minősítés mentése</button></form><form data-form="lead.stage" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${select('stage','Új állapot',Object.entries(labels).filter(([k])=>['new','qualified','booked','proposal','won','lost','replied','unsubscribed'].includes(k)))}<button>Állapot mentése</button></form></details><details><summary>Választervezet</summary><p>${esc(r.draft)}</p></details>`))}</section>`+form('lead.import','CSV import',area('csv','CSV: name,email,need','name,email,need\n'),'Importálás');
 }else if(current==='ajanlatkeszito'){
 const sample=[{name:state.profile.catalog[0]?.name||'',quantity:1,unitMinor:state.profile.catalog[0]?.unitMinor,taxPercent:state.profile.catalog[0]?.taxPercent??0}];
 html=form('proposal.create','Új ajánlat',leadSelect()+area('scope','Ügyféligény és vállalt feladat')+field('validUntil','Érvényes eddig','date','',false)+field('timeline','Ütemezés','text','',false)+area('terms','Feltételek','',false)+rows('items',sample),'Ajánlattervezet')+`<section><h2>Ajánlatok</h2>${cards(d.proposal,r=>card(r,`<p>${esc(r.scope)}</p><p>Érvényesség: ${esc(r.validUntil||'Egyeztetendő')}</p><p>${esc(r.timeline||'')}<br>${esc(r.terms||'')}</p><table><thead><tr><th>Tétel</th><th>Menny.</th><th>Bruttó</th></tr></thead><tbody>${r.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.quantity}</td><td>${(i.gross/100).toLocaleString('hu-HU')}</td></tr>`).join('')}</tbody></table><p>Nettó: ${(r.net/100).toLocaleString('hu-HU')} · Adó: ${(r.tax/100).toLocaleString('hu-HU')}<br><strong>Összesen: ${(r.gross/100).toLocaleString('hu-HU')} ${esc(r.currency)}</strong></p><div class="actions">${r.status==='draft'?button('proposal.approve','Jóváhagyom',r):r.status==='approved'?button('proposal.reportSent','Elküldöttnek jelölöm',r):''}<button class="secondary" data-print="${r.id}">Nyomtatás / PDF</button></div><details><summary>Ajánlat módosítása</summary><form data-form="proposal.edit" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${area('scope','Feladat',r.scope)}${field('timeline','Ütemezés','text',r.timeline||'',false)}${area('terms','Feltételek',r.terms||'',false)}${rows('items',r.items)}<button>Új változat mentése</button></form></details>`))}</section>`;
 }else if(current==='ugyfel-onboarding'){
 html=form('project.create','Új ügyfél indítása',field('name','Ügyfél / projekt neve')+area('checklist','Indulási ellenőrzőlista, soronként','Kapcsolattartó és elérhetőség\nCél és határidő\nSzükséges dokumentumok')+select('proposalId','Kapcsolt ajánlat (opcionális)',[['','Kézzel megerősített megrendelés'],...d.proposal.filter(r=>r.approvedRevision===r.revision).map(r=>[r.id,r.name])])+'<label class="check"><input name="confirmed" type="checkbox" required>Az ügyfél megrendelte a munkát</label>','Indítás')+`<section><h2>Projektindítások</h2>${cards(d.project,r=>card(r,`<p>${esc(r.welcome)}</p>${r.items.map(i=>`<div class="actions">${button('project.verify',`${i.verified?'✓':'○'} ${esc(i.label)}`,r,{itemId:i.id,verified:!i.verified})}</div>`).join('')}<div class="actions">${r.status==='onboarding'?button('project.start','Munka megkezdése',r):''}</div>`))}</section>`;
 }else if(current==='ugyfelkezelo'){
 html=`<div>${form('contact.create','Új kapcsolat',field('name','Név')+field('email','Email','email')+area('notes','Jegyzet','',false)+field('nextStep','Következő lépés','text','',false))}${form('task.create','Új feladat',field('title','Feladat')+field('owner','Felelős','text','',false)+field('due','Határidő','date','',false)+select('projectId','Projekt',[['','Nincs projekt'],...d.project.map(r=>[r.id,r.name])]))}</div><section><h2>Figyelmet igényel</h2>${cards(d.task.filter(r=>r.status==='open'),r=>card(r,`<p>${esc(r.owner||'Felelős tisztázandó')} · ${esc(r.due||'Határidő tisztázandó')}${r.due&&r.due<today()?' · LEJÁRT':''}</p><div class="actions">${button('task.complete','Elkészült',r)}</div><details><summary>Feladat szerkesztése</summary><form data-form="task.edit" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${field('title','Feladat','text',r.title)}${field('owner','Felelős','text',r.owner||'',false)}${field('due','Határidő','date',r.due||'',false)}<button>Változtatás mentése</button></form></details>`))}<h2>Elkészült feladatok</h2>${cards(d.task.filter(r=>r.status==='done'),r=>card(r,`<p>${esc(r.owner||'Nincs felelős')} · ${esc(r.completedAt||'')}</p>`))}<h2>Kapcsolatok</h2>${cards(d.contact,r=>card(r,`<p>${esc(r.email)}<br>${esc(r.notes)}<br>${esc(r.nextStep)}</p><details><summary>Kapcsolat szerkesztése</summary><form data-form="contact.edit" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${field('name','Név','text',r.name)}${field('email','Email','email',r.email)}${area('notes','Jegyzet',r.notes||'',false)}${field('nextStep','Következő lépés','text',r.nextStep||'',false)}<button>Változtatás mentése</button></form></details>`))}</section>`;
 }else if(current==='meeting-teendo'){
 html=form('meeting.create','Megbeszélés feldolgozása',field('title','Megbeszélés neve')+field('date','Dátum','date',today())+'<label>TXT vagy Markdown leirat<input type="file" id="transcript-file" accept=".txt,.md,text/plain,text/markdown"></label>'+area('transcript','Leirat vagy jegyzet · legfeljebb 50 000 karakter'),'Ellenőrzési munkalap')+`<section><h2>Megbeszélések</h2>${cards(d.meeting,r=>card(r,`<p>${esc(r.summary)}</p>${r.status==='approved'?`<p>${r.tasks.length} feladat létrehozva.</p><details><summary>Follow-up tervezet</summary><p>${esc(r.followupDraft)}</p></details>`:`<details open><summary>Feladatok és döntések ellenőrzése</summary><form data-form="meeting.edit" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${area('summary','Összefoglaló',r.summary)}${rows('tasks',r.tasks)}${rows('decisions',r.decisions)}<p class="hint">Minden teendőhöz és döntéshez adj szó szerinti forrásrészletet. Ismeretlen felelős és határidő maradjon üres. Először mentsd az ellenőrzött változatot.</p><button>Ellenőrzött változat mentése</button></form></details><div class="actions"><button data-ai="${r.id}" data-version="${r.version}" class="secondary">AI-tervezet előkészítése</button>${button('meeting.approve','Jóváhagyás és feladatok',r)}</div>`}<div class="actions"><button class="secondary" data-download="${r.id}">JSON export</button><button class="secondary" data-markdown="${r.id}">Markdown export</button><button class="secondary" data-csv="${r.id}">Feladatok CSV</button></div>`))}</section>`;
 }else if(current==='utankoveto'){
 html=form('followup.plan','Utánkövetés előkészítése',leadSelect()+'<p class="hint">Két tervezet készül, a profilban megadott munkanapos eltéréssel, 9 órára (hétfő–péntek; ünnepnapok nélkül), a vállalkozás időzónájában. A rendszer nem küld levelet.</p>','Tervezetek létrehozása')+`<section><h2>Utánkövetési sor</h2>${cards(d.followup,r=>card(r,`<p>${esc(r.draft)}</p><p>Esedékes: ${esc(new Date(r.due).toLocaleString('hu-HU',{timeZone:state.profile.timezone}))}</p><div class="actions">${r.status==='draft'?button('followup.reportSent','Ezt a levelet már elküldtem',r,{confirmed:true})+button('followup.cancel','Utánkövetés leállítása',r):''}</div>${r.status==='draft'?`<details><summary>Üzenet szerkesztése</summary><form data-form="followup.edit" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${area('draft','Üzenettervezet',r.draft)}<button>Tervezet mentése</button></form></details>`:''}`))}</section>`;
 }else if(current==='tudasrendszer'){
 html=`<div>${form('document.create','Tudás hozzáadása',field('title','Dokumentum neve')+select('visibility','Láthatóság',[['internal','Belső'],['public','Nyilvános']])+area('body','Dokumentum szövege'))}${form('knowledge.ask','Keresés a tudásban',field('question','Kérdés')+select('audience','Keresési kör',[['public','Csak nyilvános források'],['internal','Belső forrásokkal']]),'Források keresése')}<div id="answer"></div></div><section><h2>Tudásforrások</h2>${cards(d.document.filter(r=>r.status==='active'),r=>card(r,`<p>${esc(r.body.slice(0,350))}</p><p class="meta">${esc(r.visibility==='internal'?'Belső':'Nyilvános')}</p><div class="actions">${button('document.delete','Forrás törlése',r)}</div><details><summary>Új forrásváltozat</summary><form data-form="document.edit" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${field('title','Dokumentum neve','text',r.title)}${select('visibility','Láthatóság',r.visibility==='internal'?[['internal','Belső'],['public','Nyilvános']]:[['public','Nyilvános'],['internal','Belső']])}${area('body','Dokumentum szövege',r.body)}<button>Új változat mentése</button></form></details>`))}<h2>Emberi választ igényel</h2>${cards(d.ticket.filter(r=>r.status==='open'),r=>card(r,`<p>${esc(r.reason)}</p><form data-form="ticket.resolve" data-extra="${esc(JSON.stringify({id:r.id,version:r.version}))}">${area('answer','Ellenőrzött válasz')}<button>Kérdés lezárása</button></form>`))}</section>`;
 }else if(current==='heti-attekinto'){
 const monday=new Date(today()+'T12:00:00Z');monday.setUTCDate(monday.getUTCDate()-((monday.getUTCDay()+6)%7));html=`<div>${form('review.create','Heti pillanatkép',field('start','Hét kezdete (hétfő)','date',monday.toISOString().slice(0,10)),'Áttekintés mentése')}${form('payment.create','Pénzmozgás rögzítése','<label>Összeg<input name="amount" type="number" min="0.01" step="0.01" required></label>'+field('currency','Pénznem','text',state.profile.currency)+select('type','Típus',[['payment','Beérkezett fizetés'],['refund','Visszatérítés']])+field('date','Dátum','date',today())+field('reference','Hivatkozás'))}${form('payment.import','Pénzmozgások importálása',area('csv','CSV: amount,currency,type,date,reference','amount,currency,type,date,reference\n'),'Importálás')}</div><section><h2>Heti áttekintések</h2>${cards(d.review,r=>card(r,`<p>${esc(r.source)}<br>${r.dataState==='no-events'?'Nincs rögzített heti esemény; ez nem bizonyít nulla üzleti aktivitást.':'A rögzített adatok alapján.'}</p><div class="stats">${Object.entries(r.counts).map(([k,v])=>`<div class="stat"><strong>${v}</strong><span>${esc({leads:'Érdeklődő',bookings:'Foglalás',proposals:'Ajánlat',won:'Új ügyfél',openTasks:'Nyitott feladat'}[k])}</span></div>`).join('')}</div>${Object.entries(r.totals).map(([currency,t])=>`<p>${esc(currency)}: beérkezett ${(t.payments/100).toLocaleString('hu-HU')}, visszatérítés ${(t.refunds/100).toLocaleString('hu-HU')}, egyenleg ${(t.net/100).toLocaleString('hu-HU')}</p>`).join('')}<p>${esc(r.recommendations.join('\n'))}</p><p class="meta">Forrás frissessége: ${esc(r.freshAt)} · ${r.revision}. pillanatkép</p><button class="secondary" data-review-export="${r.id}">Riport JSON export</button>`))}</section>`;
 }else{
 const p=state.profile;html=form('profile.save','Vállalkozási profil',field('name','Vállalkozás neve','text',p.name)+area('services','Szolgáltatások, soronként',p.services.join('\n'))+field('minimumBudget','Minimum költségkeret','number',p.minimumBudget)+field('currency','Pénznem','text',p.currency)+field('timezone','Időzóna','text',p.timezone)+field('bookingUrl','HTTPS foglalási link','url',p.bookingUrl,false)+field('tone','Kommunikáció hangneme','text',p.tone)+field('followupOffsets','Utánkövetés munkanapjai (vesszővel)','text',p.followupOffsets.join(','))+['service','scope','budget','timing'].map((k,i)=>field('weight_'+k,['Szolgáltatás súlya','Terjedelem súlya','Keret súlya','Időzítés súlya'][i],'number',p.qualificationPolicy?.weights?.[k]??[40,20,20,20][i])).join('')+['budget','timing'].map(k=>`<label class="check"><input type="checkbox" name="critical_${k}" ${p.qualificationPolicy?.critical.includes(k)?'checked':''}>${k==='budget'?'Keret':'Időzítés'} kötelező a minősítéshez</label>`).join('')+rows('catalog',p.catalog),'Profil mentése');
 }
 $('#main').innerHTML=header()+(current!=='settings'?'<div class="ai-panel"><button id="business-ai" class="secondary">AI-javaslatok előkészítése</button><p class="hint">Külön indításra a modul legfeljebb 20 legfrissebb rekordja az AI-szolgáltatóhoz kerül. A javaslatokat te ellenőrzöd; a rendszer nem hajtja végre őket.</p><div id="ai-result"></div></div>':'')+`<div class="grid">${html}</div>`;
}
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.module){current=b.dataset.module;render();return;}
 if(b.dataset.addRow){b.closest('form').querySelector(`[data-rows="${b.dataset.addRow}"]`).insertAdjacentHTML('beforeend',rowEditor(b.dataset.addRow));return;}
 if(b.hasAttribute('data-remove-row')){b.closest('[data-row]').remove();return;}
 if(b.id==='settings'){current='settings';render();return;}
 try{
  if(b.dataset.reviewExport){const r=state.data.review.find(r=>r.id===b.dataset.reviewExport);download('heti-attekintes-'+r.start+'.json',JSON.stringify(r,null,2));return;}
  if(b.dataset.csv){const r=state.data.meeting.find(r=>r.id===b.dataset.csv),cell=csvCell;download('meeting-feladatok.csv','\uFEFF'+[['Feladat','Felelős','Határidő','Forrás'],...r.tasks.map(t=>[t.title,t.owner,t.due,t.evidence])].map(row=>row.map(cell).join(',')).join('\r\n'),'text/csv');return;}
  if(b.dataset.download||b.dataset.markdown){const r=state.data.meeting.find(r=>r.id===(b.dataset.download||b.dataset.markdown));download(`meeting-${r.id}.${b.dataset.download?'json':'md'}`,b.dataset.download?JSON.stringify(r,null,2):`# ${r.title}\n\n${r.summary}\n\n${r.tasks.map(t=>`- ${t.title} (${t.owner||'ismeretlen'}; ${t.due||'ismeretlen'})\n  Forrás: ${t.evidence}`).join('\n')}`,b.dataset.download?'application/json':'text/markdown');return;}
  if(b.dataset.print){const r=state.data.proposal.find(r=>r.id===b.dataset.print);const html=`<!doctype html><html lang="hu"><meta charset="utf-8"><title>Ajánlat</title><h1>${esc(state.profile.name)} · Ajánlat</h1><h2>${esc(r.name)}</h2><p>${esc(r.scope)}</p><p>Érvényesség: ${esc(r.validUntil||'Egyeztetendő')}</p><p>${esc(r.timeline||'')}</p><p>${esc(r.terms||'')}</p>${r.items.map(i=>`<p>${esc(i.name)} × ${i.quantity}: ${i.gross/100} ${esc(r.currency)}</p>`).join('')}<p>Nettó: ${r.net/100}; adó: ${r.tax/100}; összesen: ${r.gross/100} ${esc(r.currency)}</p><p>${r.revision}. változat · ${esc(labels[r.status])}</p><p>A böngésző Nyomtatás parancsával menthető PDF-be.</p></html>`;download(`ajanlat-${r.id}.html`,html,'text/html');notice('Az ajánlat letöltve. Megnyitás után a Nyomtatás menüből PDF-be menthető.');return;}
  if(b.id==='business-ai'){b.disabled=true;const requestModule=current;const result=await request('/api/ai/business',{module:requestModule});if(current!==requestModule||!$('#ai-result')){notice('Az AI-tervezet elkészült, de közben másik modulra váltottál.');return;}$('#ai-result').innerHTML=`<article class="card"><h2>Ellenőrzésre váró AI-javaslat</h2>${result.quotes.map(q=>`<blockquote>${esc(q.quote)}<div class="meta">Forrás: ${esc(q.sourceId)} · ${q.sourceVersion}. változat</div></blockquote>`).join('')}<h3>Megfontolandó következő lépések</h3><ul>${result.suggestions.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>${result.draft?`<h3>Szerkesztendő üzenettervezet</h3><p>${esc(result.draft)}</p>`:''}</article>`;return;}
  if(b.dataset.action||b.dataset.ai){b.disabled=true;if(b.dataset.ai)await request('/api/ai/meeting',{id:b.dataset.ai,version:Number(b.dataset.version)});else await action(b.dataset.action,JSON.parse(b.dataset.input));await refresh();notice('Mentve.');}
 }catch(error){notice(error.message);}finally{b.disabled=false;}
});
document.addEventListener('submit',async e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();if(f.dataset.busy)return;f.dataset.busy='1';const b=f.querySelector('button[type=submit]')||f.querySelector('button:not([type])');b.disabled=true;
 try{const data=Object.fromEntries(new FormData(f)),name=f.dataset.form;Object.assign(data,JSON.parse(f.dataset.extra));
 for(const key of ['items','tasks','decisions','catalog'])if(f.querySelector(`[data-rows="${key}"]`))data[key]=readRows(f,key);
 for(const key of ['minimumBudget','amountMinor'])if(key in data)data[key]=Number(data[key]);
 if(name==='payment.create'){if(!/^\d+(?:\.\d{1,2})?$/.test(data.amount))throw new Error('Érvényes, legfeljebb két tizedesjegyes összeget adj meg.');data.amountMinor=Math.round(Number(data.amount)*100);}
 if(name==='profile.save'){data.services=data.services.split('\n').filter(Boolean);data.version=state.profile.version;data.followupOffsets=data.followupOffsets.split(',').map(v=>Number(v.trim()));data.qualificationPolicy={weights:Object.fromEntries(['service','scope','budget','timing'].map(k=>[k,Number(data['weight_'+k])])),critical:['service','scope',...['budget','timing'].filter(k=>f.elements['critical_'+k].checked)]};}
 if(name==='project.create'){data.confirmed=f.elements.confirmed.checked;data.checklist=data.checklist.split('\n').filter(Boolean);}
 if(name==='lead.qualify'){data.scores=Object.fromEntries(['service','scope','budget','timing'].map(k=>[k,data[k]===''?null:Number(data[k])]));data.scores.excluded=f.elements.excluded.checked;}
 const result=await action(name,data);if(name==='knowledge.ask'){$('#answer').innerHTML=`<article class="card"><p>${esc(result.answer||'Nincs megfelelő forrás. Emberi válaszra váró kérdés rögzítve.')}</p>${result.sources.map(s=>`<h3>${esc(s.title)} · ${s.version}. változat</h3><p>${esc(s.quote)}</p>`).join('')}</article>`;return;}await refresh();notice('Mentve.');
 }catch(error){notice(error.message);}finally{b.disabled=false;delete f.dataset.busy;}
});
$('#restore').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw new Error('A mentés legfeljebb 2 MiB lehet.');await request('/api/restore',JSON.parse(await file.text()));await refresh();notice('Mentés visszaállítva.');}catch(error){notice(error.message);}});
document.addEventListener('change',async e=>{if(e.target.id!=='transcript-file')return;try{const file=e.target.files[0];if(!file)return;if(!/\.(txt|md)$/i.test(file.name)||file.size>200000)throw new Error('Legfeljebb 200 kB TXT/MD fájl adható meg.');const content=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(!content.trim()||content.length>50000||content.includes('\0'))throw new Error('A leirat nem üres UTF-8 szöveg legyen, legfeljebb 50 000 karakter.');e.target.closest('form').elements.transcript.value=content;notice('Leirat betöltve; ellenőrizd, majd mentsd.');}catch(error){notice(error.message);}});
refresh().catch(e=>{$('#main').textContent=e.message;});
